config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # development環境ではメールを送信する代わりに、指定のブラウザでプレビュー
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'reservations/reserve'
  get 'reservations/show'
 root to: 'books#index'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :books
  resources :reservations
  resources :lendings
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image do |attachable|
        attachable.variant :display, resize_to_limit: [400, 400]
      end
   
    has_many :users_lendings, through: :lendings, source: :book
    has_many :users_reservations, through: :reservations, source: :book
    validates :title, presence: true
    validates :author, presence: true

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @lending_books = Lending.where(status: 0)
    # @reservation_books = current_user.reservations.where(status: 0) unless current_user.nil?
    @reservation_books = Reservation.where(status: 0)
    @users = User.all

    @reserved_books = Reservation.where("reserved_start <= ?", Date.yesterday)
    @reserved_books.destroy_all
  end

  def show
    @lendings_status = Lending.all.where(status:0, book_id:params[:id]).first
    @reservation_status_list = Reservation.all.where('status = ? and reserved_start >= ? and book_id = ?', 0, Date.today, params[:id])
    @book = Book.find(params[:id])
    @lending_book = Lending.where(user_id: current_user.id, book_id: @book,status: 0).first unless current_user.nil?
    @reservation_book = Reservation.where(user_id: current_user.id, book_id: @book, status: 0).first unless current_user.nil?
        if !current_user.nil? && !@lending_book.nil?
          redirect_to lending_path
        elsif !current_user.nil? && !@reservation_book.nil?
          redirect_to reservation_path
        end      
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    # 登録が成功したら一覧へ、失敗したらフォームをリダイレクトさせる。
    if book.save!
      redirect_to books_url, notice: "「#{book.title}」を登録しました。"
    else
      render :new, alert: "入力が間違っています。"
    end
  end

  def edit
    redirect_to books_url
  end

  # 本を借りるアクション
  def lend
    redirect_to books_url
  end

  # 本を予約するアクション
  def reserve
    redirect_to books_url
  end

  private

  # strong_parameters,,,登録画面でハッシュの内容をそのまま送らないようにしている。
  def book_params
    # stockカラムを追加したら修正する
    params.require(:book).permit(:title, :author, :image)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @book) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :author %>
      <%= f.text_field :author %>

      <%= f.label :image %>
      <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>

      <%= f.submit "本を登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<h1>本の編集ページです。</h1>

app/views/books/index.html.erb
<div class="wrapper">


<h3 class="page_title">本一覧</h3>

    <% @books.each do |book| %>

        <%= link_to book_path(book.id) , class: "index_wrap" do %>
            <div class="index_list_wrap">
                <div class="index_image_wrap">
                    <%= image_tag book.image , class: "index_image" %>
                </div>
                
                <div>
                    <p class="index_list_title">『&nbsp;<%= book.title%>&nbsp;』</p>
                    <p class="index_auther"><span class="ml-15"><%= book.author %></span><span class="ml-10">著</span></p>
                    <div class="index_status_wrap">

                        <% if current_user.nil? && !@lending_books.find_by(book_id: book).nil?%>
                            <p>貸出中</p>
                        <% elsif current_user.nil? && @lending_books.find_by(book_id: book).nil? %>
                            <p>貸出受付中</p>
                        <% end %>

                        <%#<% if !current_user.nil? && !@reservation_books.find_by(book_id: book).nil? %>
                            <%#<p>予約中</p>
                        <%#<% end %>

                          <%# userログイン中 %> 
                        <% if !current_user.nil? && current_user.status == 1 %>

                            <% if !@lending_books.find_by(book_id: book).nil? %>
                                <p>貸出中</p>
                            <% elsif %>
                                <p>貸出受付中</p>
                            <% end %>

                            <% if !@reservation_books.where(user_id:current_user.id ,book_id: book).empty? %>
                                <p>予約中</p>
                            <% end %> 

                        <% end %>

                        <%# adminログイン中 %> 
                        <% if !current_user.nil? && current_user.status == 0 %>
                            
                            <% if !@lending_books.where(book_id: book).empty? %>
                                <p><span style="margin-left:-4px; border-radius : 3px 0 0 3px ; padding:5px ; color:#fff ; background-color: palevioletred;">貸出中</span>
                                    <span style="font-weight:bold; margin:0 3px;"></span><%= @lending_books.find_by(user_id: @users).user.name %>
                                    <span style="font-weight:bold; margin:0 3px;"></span><%= @lending_books.find_by(user_id: @users).user.email %>
                                </p>
                            <% end %>

                            <% if !@reservation_books.where(book_id: book).empty? %>
                                <p>予約中</p>
                            <% end %>

                        <% end %>

                    </div>
                </div>
            </div>
        <% end %>

    <% end %>
</div>

app/views/books/new.html.erb
<h2>本管理　＞　本登録</h2>

<%#= link_to '本一覧へもどる', books_path, class: 'nav-link' %>

<%= render partial: 'form', locals: { book: @book }%>

app/views/books/show.html.erb
<h1> <%= @book.title %> </h1>
<% if @book.image.attached? %>
    <%= image_tag @book.image.variant(:display) %>
<% end %>

<% if !@lendings_status.nil? %>
    <p>貸出中</p>
<% else %>
    <p>貸出可能</p>
<% end %>

<%= form_with url: reservations_path, local: true do |f| %>
    <%= f.date_field :reserved_start,value: Date.today.strftime('%Y-%m-%d'),min: Date.today.strftime('%Y-%m-%d'), class: 'form-control' %>から
    <%= f.date_field :reserved_end,value: Date.today.next_day(7).strftime('%Y-%m-%d'),min: Date.today.strftime('%Y-%m-%d'), class: 'form-control' %>まで

    <%# idをhiddenで送る %>
    <%= f.hidden_field :book_id, :value => params[:id] %>
    <%#= f.hidden_field :user_id, :value => current_user.id unless current_user.nil? %>

    <% if @lendings_status.nil? %>
        <%= f.submit "借りる",{formaction: lendings_path, class: "btn btn-primary"} %>
    <% else %>
        <%= f.submit "借りる",{formaction: lendings_path, class: "btn btn-primary", disabled: true}%>
    <% end %>
    <%= f.submit "予約する", class: "btn btn-primary" %>
<% end %>

<% if !@reservation_status_list.empty? %>
    <p>以下の予定が入っています。</p>
    <p>日程が被らないように貸出・予約をしましょう。</p>
    <% @reservation_status_list.each do |day|%>
     <p> <%= day["reserved_start"] %> ~ <%= day["reserved_end"] %> </p>
    <% end %>
<% elsif !@lendings_status.nil? == true then %> 
    <p>現在貸出中です。<%= @lendings_status["return_date"] %>に返却される予定です。</P>
<% end %>