config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # development環境ではメールを送信する代わりに、指定のブラウザでプレビュー
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'reservations/reserve'
  get 'reservations/show'
 root to: 'books#index'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :books
  resources :reservations
  resources :lendings
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
      @reservation_books = current_user.reservations.where(status: 0).order(:reserved_start)
  end

  def show
    @reservation_book = current_user.reservations.where(book_id:params[:id], status:0).first
  end

  def create
    if !current_user.nil?
      @reservation_book = Reservation.new(reservation_params(params))
      
      if @reservation_book.save
          redirect_to reservations_path, notice: "予約完了"
      else
          render :new
      end
    else
      redirect_to new_user_session_path
    end
  end

  def edit
    current_user.reservations.where(book_id: params[:id], status: 0).first.destroy
    redirect_to reservations_path, notice:"予約を取り消しました"
  end

  private
  def reservation_params(data)
      @reservation_books = {user_id: current_user.id, book_id: data[:book_id], reserved_start: data[:reserved_start], reserved_end: data[:reserved_end]}
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<div class="wrapper">
    <h3 class="page_title">予約した本一覧</h3>

    <% if !@reservation_books.nil? %>
        <% @reservation_books.each do |reservation_book| %>
            <%= link_to reservation_path(reservation_book.book_id), class: "index_wrap" do %>
                <div class="index_list_wrap">
                    <div class="index_image_wrap">
                        <%= image_tag reservation_book.book.image , class: "index_image" %>
                    </div>
                    <div>
                        <p class="index_list_title">『&nbsp;<%= reservation_book.book.title%>&nbsp;』</p>
                        <p class="index_auther"><span class="ml-15"><%= reservation_book.book.author%></span><span class="ml-10">著</span></p>
                        <p class="index_res_period">
                            <%= reservation_book.reserved_start %>  から  <%= reservation_book.reserved_end %> まで
                        </p>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/reservations/reserve.html.erb
<h1>Reservations#reserve</h1>
<p>Find me in app/views/reservations/reserve.html.erb</p>

app/views/reservations/show.html.erb
<div class="res_show">
    <div>
        <%= image_tag @reservation_book.book.image, {class: "book_image"} %>
    </div>
    <div>
        <div class="book_title">
            <%= @reservation_book.book.title %>
        </div>
        <div class="book_author">
            <%= @reservation_book.book.author %> 著
        </div>
        <div class="index_status_wrap status_size">
            予約しています
        </div>
        <div>
            <%= button_to "予約を取り消す", {controller: "reservations", action: "edit"}, {method: :get, class: "res_can_button"} %>
        </div>
        <div class="show_res_period_text">
            以下の日程で予約しています
        </div>
        <p class="show_res_period">
            <%= @reservation_book.reserved_start %> から
            <%= @reservation_book.reserved_end %> まで
        </p>
    </div>
</div>