config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # development環境ではメールを送信する代わりに、指定のブラウザでプレビュー
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'reservations/reserve'
  get 'reservations/show'
 root to: 'books#index'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :books
  resources :reservations
  resources :lendings
end

app/models/lending.rb
class Lending < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :user_id, presence: true
  validates :book_id, presence: true

  private
    def return_date_remindmail
      RemindMailerJob.set(wait_until: remind_day).perform_later(self)
    end

    def remind_day
      self.return_date - 2.day - 15.hour
    end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController

    def index
        # ログインしたユーザーの借りている本を表示させる
        @lending_books = current_user.lendings.where(status: 0)
        
    end

    def show
        @reservation_books = current_user.lendings.where(book_id:params[:id], status:0).first
        @lending_book = current_user.lendings.where(book_id:params[:id], status:0).first
    end

    def create
        if !current_user.nil?
            @lending_book = Lending.new(lending_params(params))
            if @lending_book.save
                redirect_to lendings_url, notice: "貸出完了"
            else
                render :show
            end
        else
            redirect_to new_user_session_path
        end
    end

    def edit
        current_user.lendings.where(book_id: params[:id], status: 0).first.update(status:1)
        redirect_to book_path, notice:"本を返却しました"
    end

    private
    def lending_params(data)
        @lending_books = {user_id: current_user.id, book_id: data[:book_id], lend_date: data[:reserved_start], return_date: data[:reserved_end]}
    end

end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/lendings/index.html.erb
<div class="wrapper">
    <h3 class="page_title">借りた本一覧</h3>

    <% if !@lending_books.nil? %>
        <% @lending_books.each do |lending_book| %>
            <%= link_to lending_path(lending_book.book_id), class: "index_wrap" do %>
                <div class="index_list_wrap">
                    <div class="index_image_wrap">
                        <%= image_tag lending_book.book.image , class: "index_image" %>
                    </div>
                    <div>
                        <p class="index_list_title">『&nbsp;<%= lending_book.book.title%>&nbsp;』</p>
                        <p class="index_auther"><span class="ml-15"><%= lending_book.book.author%></span><span class="ml-10">著</span></p>
                        <p class="index_res_period">
                            <%= lending_book.lend_date %>  から  <%= lending_book.return_date %> まで
                        </p>
                    </div>
                </div>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/lendings/show.html.erb
<div class="res_show">
    <div>
        <%= image_tag @lending_book.book.image, {class: "book_image"} %>
    </div>
    <div>
        <div class="book_title">
            <%= @lending_book.book.title %>
        </div>
        <div class="book_author">
            <%= @lending_book.book.author %> 著
        </div>
        <div class="index_status_wrap status_size">
            貸出しています
        </div>
        <div>
            <%= button_to "本を返却する", {controller: "lendings", action: "edit"}, {method: :get, class: "res_can_button"} %>
        </div>

        <% if @lending_book.return_date > Date.yesterday %>
            <div class="show_res_period_text">
                以下の日程で貸出しています
            </div>
            <p class="show_res_period">
                <%= @lending_book.lend_date %> から
                <%= @lending_book.return_date %> まで
            </p>
        <% else %>
            <p class="return_alert">返却日が過ぎています！<br>早めに返却をお願いします！</p>
        <% end %>
    </div>
</div>