config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # development環境ではメールを送信する代わりに、指定のブラウザでプレビュー
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get 'reservations/reserve'
  get 'reservations/show'
 root to: 'books#index'
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :books
  resources :reservations
  resources :lendings
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="header_wrapper">
      <div class="header_wrap">
        <%# <%= link_to "CODEBASE BOOKS", books_path ,class: "logo" %>
        <%= render "devise/shared/notifications" %>
        <%= link_to "本一覧", books_path, class: "nav-link" %>
        <% if !current_user.nil? && current_user.status == 0 %>
          <%= link_to "本の登録", new_book_path, class: "btn btn-primary" %>
          <%= link_to "ユーザー一覧", users_index_path, class: "btn btn-primary" %>
          <%= current_user.name %>
          <%= link_to "ログアウト", destroy_user_session_path,data: {"turbo-method": :delete} %>
        <% elsif user_signed_in? %>
          <%= link_to "借りている本", lendings_path %>
          <%= link_to "予約している本", reservations_path %>
          <%= current_user.name %>
          <%= link_to "ログアウト", destroy_user_session_path,data: {"turbo-method": :delete} %>
        <% else %>
          <%= link_to "新規登録", new_user_registration_path %>
          <%= link_to "ログイン", new_user_session_path %>
        <% end %>
      </div>
    </div>

    <%= yield %>

  </body>
</html>